spring:
  datasource:
    username: postgres
    password: password
      url : jdbc:postgresql://localhost:5432/my_first_db
      driver-classlname: org.postgresql.Driver
---
spring:
  jpa:
    generate-ddl: true