spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/my_first_db
    driver-class-name: org.postgresql.Driver
---
spring:
  jpa:
    generate-ddl: true