spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/my_first_db
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
logging:
  level:
    root: INFO
    com.example.client.NBUClient: ${NBU_CLIENT_LOG_LEVEL:DEBUG}

com.example.client.url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json
