GET http://localhost:8080/currency
###
GET http://localhost:8080/currency?valcode=USD
###
GET http://localhost:8080/currency?id=2
###
POST http://localhost:8080/currency
Content-Type: application/json

[{"valcode":"USD"},
{"valcode":"EUR"},
{"valcode":"GBP"}]
###
DELETE http://localhost:8080/currency/2
##№


###
POST http://localhost:8080/currency-rate?valcode=USD&date=2019-07-19